"""apply_worker: add apply_status_history table

Revision ID: 1d2e3f4a5b6c
Revises: 5c8a9b0d1e2f
Create Date: 2026-06-16 16:30:00.000000

Adds the ``apply_status_history`` table that backs the
:class:`ApplyStatusHistory` model introduced in M5, issue #49. Every
:class:`ApplyJob` status transition the apply worker performs
(enqueue, claim_next, complete, fail, cancel) appends one row so the
dashboard can render a per-job timeline and the operator can debug
failed runs after the fact.

Schema
------

* ``id``            — UUID primary key.
* ``job_id``        — FK to ``apply_jobs.id`` (``ondelete=CASCADE`` so
                      a hard-deleted job takes its history with it).
* ``from_status``   — the status the job transitioned *from*; ``NULL``
                      for the initial creation row (no prior state).
* ``to_status``     — the status the job transitioned *to*; one of
                      the :class:`ApplyJobStatus` values.
* ``error``         — error message for the transition; ``NULL`` for
                      successful transitions.
* ``metadata_json`` — JSON-encoded extra context (retry attempt
                      number, retryable flag, ``next_run_at``, etc.).
                      ``NULL`` when no extra context is relevant.
* ``created_at``    — server-side timestamp.

Indexes
-------

* ``ix_apply_status_history_job_id_created_at`` composite on
  ``(job_id, created_at)`` backs :meth:`ApplyStatusHistoryRepository.list_by_job`
  and keeps the per-job timeline query cheap as the table grows.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain. The branch is the single head at the time of writing
(``5c8a9b0d1e2f`` — apply_jobs), so the chain stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d2e3f4a5b6c"
down_revision: str | Sequence[str] | None = "5c8a9b0d1e2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "apply_status_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("from_status", sa.String(length=50), nullable=True),
        sa.Column("to_status", sa.String(length=50), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_apply_status_history"),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["apply_jobs.id"],
            name="fk_apply_status_history_job_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_apply_status_history_job_id_created_at",
        "apply_status_history",
        ["job_id", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_apply_status_history_job_id_created_at", table_name="apply_status_history")
    op.drop_table("apply_status_history")
