"""apply_worker: add apply_jobs table

Revision ID: 5c8a9b0d1e2f
Revises: 8f1c2d3e4f56
Create Date: 2026-06-16 16:00:00.000000

Adds the ``apply_jobs`` table that backs the ``features/apply_worker``
vertical slice (M5, issue #43) — the queue the apply worker drains to
submit applications to hh.ru (or, in tests, a fake HH client).

Schema
------

* ``id``                       — UUID primary key.
* ``match_id``                 — FK to ``vacancy_matches.id`` (issue
                                 #10). ``UNIQUE`` so a re-acceptance
                                 does not spawn a second row.
* ``user_id``                  — FK to ``users.id`` (issue #11).
                                 Denormalised so ownership checks
                                 never have to join through the match
                                 table.
* ``vacancy_id``               — FK to ``vacancies.id`` (issue #6).
                                 Denormalised so the worker can
                                 ``SELECT`` the queue without joining
                                 through ``vacancy_matches``.
* ``status``                   — one of ``queued`` / ``running`` /
                                 ``succeeded`` / ``failed`` /
                                 ``cancelled`` / ``dead_letter``.
                                 ``String(20)`` mirrors the model's
                                 M5 #43 contract.
* ``attempts``                 — number of times the worker has tried
                                 this job (incremented on every
                                 :meth:`ApplyJobRepository.mark_attempt`).
* ``last_error``               — text of the most recent error; reset
                                 on a successful run.
* ``next_run_at``              — earliest UTC timestamp at which the
                                 worker may re-attempt the job.
                                 ``NULL`` for fresh rows.
* ``idempotency_key``          — SHA-256 hex digest of
                                 ``f"{user_id}|{vacancy_id}|{match_id}"``.
                                 ``UNIQUE`` so a misbehaving caller
                                 cannot double-enqueue the same match.
* ``external_application_id``  — hh's identifier for the resulting
                                 application; ``NULL`` until
                                 :attr:`ApplyJobStatus.SUCCEEDED`.
* ``created_at``               — server-side timestamp.
* ``updated_at``               — server-side ``onupdate`` timestamp.
* ``started_at``               — wall-clock boundary stamped on
                                 ``claim_next``.
* ``finished_at``              — wall-clock boundary stamped when
                                 the row reaches a terminal state.

Indexes
-------

* ``ix_apply_jobs_status_next_run_at`` composite on
  ``(status, next_run_at)`` backs the worker's queue scan
  (``WHERE status = 'queued' AND next_run_at <= now()``).
* ``ix_apply_jobs_user_id`` single column on ``user_id`` for the
  per-user listing on the dashboard.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain. The branch is the single head at the time of writing
(``8f1c2d3e4f56`` — screening questions / answers), so the chain
stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c8a9b0d1e2f"
down_revision: str | Sequence[str] | None = "8f1c2d3e4f56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "apply_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("vacancy_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="queued",
        ),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("external_application_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_apply_jobs"),
        sa.UniqueConstraint("match_id", name="uq_apply_jobs_match_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_apply_jobs_idempotency_key"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["vacancy_matches.id"],
            name="fk_apply_jobs_match_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_apply_jobs_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name="fk_apply_jobs_vacancy_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_apply_jobs_status_next_run_at",
        "apply_jobs",
        ["status", "next_run_at"],
    )
    op.create_index(
        "ix_apply_jobs_user_id",
        "apply_jobs",
        ["user_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_apply_jobs_user_id", table_name="apply_jobs")
    op.drop_index("ix_apply_jobs_status_next_run_at", table_name="apply_jobs")
    op.drop_table("apply_jobs")
