"""writing_style_memory: add style_memory_entries table

Revision ID: 71a2b3c4d5e6
Revises: eb6c1c51520c
Create Date: 2026-06-17 11:00:00.000000

Adds the ``style_memory_entries`` table that backs the
``writing_style_memory`` slice (M8, issue #66). The table stores a
per-user history of cover letters the user has accepted, plus a
deterministic ``style_summary`` for each one. The slice is a **learned**
layer on top of the static :mod:`cover_letter_style` preferences: every
time the user accepts a match with a cover letter, a
:class:`StyleMemoryEntry` is appended to the user's memory and can be
read back through the API.

Schema
------

* ``id`` — UUID primary key.
* ``user_id`` — FK to ``users.id`` (owned by the auth slice, #11). The
  column is indexed because the read path (``list_for_user`` /
  ``get_aggregated``) always filters on it.
* ``cover_letter_id`` — FK to ``cover_letter_drafts.id``
  (``ON DELETE SET NULL``). The column is nullable and indexed so a
  draft that is purged by the housekeeping job does not orphan its
  style memory entry — the entry remains useful as a historical hint
  even when the underlying draft is gone.
* ``letter_text`` — the full text of the accepted cover letter. The
  column is ``Text`` so a long letter does not require a length
  cap. Future slices may re-derive summaries from a single source of
  truth without joining another table.
* ``style_summary`` — the deterministic, MVP summary produced by
  :func:`apply_pilot.features.writing_style_memory.summariser.summarise_letter`.
  It is the primary surface the API exposes today, so callers do not
  need a second pass to compute it.
* ``created_at`` — server-side timestamp with the standard
  ``CURRENT_TIMESTAMP`` default used by the rest of the chain.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (CHAR(36)) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations
in this chain. The branch is a merge of the two heads that existed
at the time of writing (``eb6c1c51520c`` — search profiles
is_preferred, and ``f1a2b3c4d5e6`` — hh resume links), so the chain
stays linear.

.. note::
   M10 (issue #204) removed the HH OAuth / apply path, including the
   ``f1a2b3c4d5e6_hh_add_hh_resume_links_table`` migration. The
   ``down_revision`` above used to be the tuple
   ``("eb6c1c51520c", "f1a2b3c4d5e6")``; we now point only at
   ``eb6c1c51520c`` because the other branch is gone.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71a2b3c4d5e6"
# Originally merged the ``eb6c1c51520c`` and ``f1a2b3c4d5e6`` heads.
# M10 dropped the ``f1a2b3c4d5e6`` migration, so the parent is now
# only ``eb6c1c51520c``.
down_revision: str | Sequence[str] | None = "eb6c1c51520c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "style_memory_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("cover_letter_id", sa.String(length=36), nullable=True),
        sa.Column("letter_text", sa.Text(), nullable=False),
        sa.Column("style_summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letter_drafts.id"],
            name=op.f("fk_style_memory_entries_cover_letter_id_cover_letter_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_style_memory_entries_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_style_memory_entries")),
    )
    op.create_index(
        op.f("ix_style_memory_entries_user_id"),
        "style_memory_entries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_style_memory_entries_cover_letter_id"),
        "style_memory_entries",
        ["cover_letter_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_style_memory_entries_cover_letter_id"), table_name="style_memory_entries"
    )
    op.drop_index(op.f("ix_style_memory_entries_user_id"), table_name="style_memory_entries")
    op.drop_table("style_memory_entries")
