"""scoring: add LLM scoring fields to vacancy_matches

Revision ID: 8789b1e18428
Revises: f0e1a2b3c4d5
Create Date: 2026-06-15 21:03:39.256034

Adds four columns to the ``vacancy_matches`` table so the LLM
scoring pipeline (issue #29) can persist the full provenance of a
score in one row:

* ``prompt_version`` — the active :class:`PromptVersion` that
  produced the score (``String(64)``, nullable). Used by auditors
  to know which template a historical score came from.
* ``confidence`` — the LLM's self-reported confidence in
  ``[0.0, 1.0]`` (``Float``, nullable).
* ``scored_at`` — UTC timestamp captured when the scoring pass
  completed (``DateTime(timezone=True)``, nullable). Differs from
  ``updated_at`` which is set on *any* mutation.

The new columns are all nullable so existing rows (which were scored
manually or predate the LLM pipeline) remain valid. The ``"new"``
status branch continues to allow ``score IS NULL``; the scoring
service uses :meth:`VacancyMatchRepository.list_pending` to find
matches where ``score`` is still ``NULL`` and ``status`` is
``"new"`` or ``"review"``.

The migration is hand-written (not autogenerated) to keep the
column types portable across sqlite (no native ``FLOAT`` precision
guarantees) and PostgreSQL — same convention as the rest of the
migrations in this chain.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8789b1e18428"
down_revision: str | None = "f0e1a2b3c4d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "vacancy_matches",
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "vacancy_matches",
        sa.Column("confidence", sa.Float(), nullable=True),
    )
    op.add_column(
        "vacancy_matches",
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("vacancy_matches", "scored_at")
    op.drop_column("vacancy_matches", "confidence")
    op.drop_column("vacancy_matches", "prompt_version")
