"""screening: add screening_questions and screening_question_answers tables

Revision ID: 8f1c2d3e4f56
Revises: b2c3d4e5f6a7
Create Date: 2026-06-16 10:58:00.000000

Adds the two tables that back the ``features/screening`` vertical slice
(M3, issue #34): the questions a vacancy asks the candidate, and the
LLM-suggested answers per user.

Schema
------

``screening_questions``:

* ``id``              — UUID primary key.
* ``vacancy_id``      — FK to ``vacancies.id`` (issue #23). Cascades
                        on delete so removing a vacancy drops its
                        questions. Indexed for the "all questions
                        for this vacancy" listing.
* ``question_text``   — the question, free text.
* ``question_order``  — 0-based ordering index assigned by the
                        service. The default is 0 (set in the ORM
                        model); ``add_questions_to_vacancy``
                        populates it with sequential values.
* ``created_at``      — server-side timestamp.

``screening_question_answers``:

* ``id``              — UUID primary key.
* ``question_id``     — FK to ``screening_questions.id``. Cascades
                        on delete so removing a question drops its
                        answers.
* ``user_id``         — FK to ``users.id`` (issue #11). Cascades on
                        delete so removing a user drops their
                        answers. Indexed for the per-user listing
                        that powers the ``GET /screening/answers``
                        endpoint.
* ``answer_text``     — the LLM-suggested answer body.
* ``prompt_version``  — ``<name>@<semver>`` stamp mirroring the
                        :class:`PromptVersion` value object. The
                        service fills this with
                        :data:`job_apply.features.screening.prompts.SCREENING_ANSWER_PROMPT_VERSION`.
* ``model_used``      — the LLM model name that produced the text.
                        ``NULL`` when the client does not expose a
                        model attribute.
* ``created_at`` / ``updated_at`` — server-side timestamps.
* Unique constraint on ``(question_id, user_id)`` — backs the
  service-level idempotency contract on
  :meth:`ScreeningService.generate_answer`.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain. The branch is the single head at the time of writing
(``b2c3d4e5f6a7`` — cover_letter's ``cover_letter_drafts`` table), so
the chain stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f1c2d3e4f56"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "screening_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vacancy_id", sa.String(length=36), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("question_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_screening_questions"),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name="fk_screening_questions_vacancy_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_screening_questions_vacancy",
        "screening_questions",
        ["vacancy_id"],
    )

    op.create_table(
        "screening_question_answers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_screening_question_answers"),
        sa.UniqueConstraint(
            "question_id",
            "user_id",
            name="uq_screening_question_answers_question_user",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["screening_questions.id"],
            name="fk_screening_question_answers_question_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_screening_question_answers_user_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_screening_question_answers_user",
        "screening_question_answers",
        ["user_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_screening_question_answers_user", table_name="screening_question_answers")
    op.drop_table("screening_question_answers")
    op.drop_index("ix_screening_questions_vacancy", table_name="screening_questions")
    op.drop_table("screening_questions")
