"""scoring: add confidence column to vacancy_matches

Revision ID: 9b1c2d3e4f56
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 23:00:00.000000

Adds the single ``confidence`` column the M3 deep-scoring pipeline
(issue #29) persists alongside the LLM score, on top of the
``explanation`` / ``prompt_version`` / ``scored_at`` columns that
issue #30 introduced.

* ``confidence`` — Float. The LLM's self-reported certainty in
  ``[0.0, 1.0]``. ``None`` until the row has been through
  :class:`ScoringService`. Stored as ``Float`` (not ``Numeric``) so
  the column is portable across sqlite and PostgreSQL — the LLM
  itself produces a float, so the precision is sufficient.

The migration is hand-written (not autogenerated) for cross-dialect
portability. Branches off the single head introduced by issue #30
(``a1b2c3d4e5f6``) so the chain remains linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b1c2d3e4f56"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "vacancy_matches",
        sa.Column("confidence", sa.Float(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("vacancy_matches", "confidence")
