"""apply_worker: add apply_rate_limit_events table

Revision ID: 9f1a2b3c4d5e
Revises: 1d2e3f4a5b6c
Create Date: 2026-06-16 18:00:00.000000

Adds the ``apply_rate_limit_events`` table that backs the
:class:`~apply_pilot.features.apply_worker.models.ApplyRateLimitEvent`
model introduced in M5, issue #46. Every successful
:meth:`~apply_pilot.features.apply_worker.service.ApplyJobService.enqueue_for_match`
call appends one row so the per-user hourly / daily windows can be
computed by counting rows in the rolling ``[now - window, now]``
range.

Schema
------

* ``id``          — UUID primary key.
* ``user_id``     — FK to ``users.id`` (``ondelete=CASCADE`` so a
                   hard-deleted user takes their rate-limit events
                   with it).
* ``key``         — the operation the event guards (M5 ships a single
                   key, ``"apply"``; the column is wide enough to
                   support additional keys without a schema change).
* ``occurred_at`` — server-side timestamp; populated by the database
                   at insert time so clock skew between application
                   processes cannot double-count events.

Indexes
-------

* ``ix_apply_rate_limit_events_user_id_key_occurred_at`` composite on
  ``(user_id, key, occurred_at)`` backs both
  :meth:`InMemoryRateLimiter.check` /
  :meth:`SqlRateLimiter.check` (the per-user window count) and the
  ``GET /apply-jobs/limits`` HTTP endpoint. Keeping all three columns
  in the index lets the database answer the count + reset queries
  with a single index seek.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain. The branch follows on from ``1d2e3f4a5b6c``
(``apply_status_history``) so the chain stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f1a2b3c4d5e"
down_revision: str | Sequence[str] | None = "1d2e3f4a5b6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "apply_rate_limit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_apply_rate_limit_events"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_apply_rate_limit_events_user_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_apply_rate_limit_events_user_id_key_occurred_at",
        "apply_rate_limit_events",
        ["user_id", "key", "occurred_at"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_apply_rate_limit_events_user_id_key_occurred_at",
        table_name="apply_rate_limit_events",
    )
    op.drop_table("apply_rate_limit_events")
