"""scoring: add prompt_versions registry and extend vacancy_matches with LLM scoring fields

Revision ID: a1b2c3d4e5f6
Revises: 7b1a4c5d8e2f, f0e1a2b3c4d5
Create Date: 2026-06-15 23:30:00.000000

Issue #30 (M3: Store score, explanation, and prompt version). Two
changes land in a single revision so the migration chain stays
linear:

1. ``vacancy_matches`` — three new nullable columns: ``explanation``
   (TEXT), ``prompt_version`` (VARCHAR(50)) and ``scored_at``
   (DateTime(timezone=True)). All three are NULL on freshly-ingested
   matches, so the change is backward-compatible with rows that
   pre-date the LLM scoring pipeline (issue #29).

2. ``prompt_versions`` — new table that backs the
   :class:`PromptVersionRegistry`. Each row is a single revision of a
   prompt template (``vacancy_scoring``, ``cover_letter``). The schema
   enforces:

   * ``UNIQUE(name, version)`` — no duplicate revisions of the same
     prompt.
   * partial UNIQUE INDEX on ``(name) WHERE is_active`` — exactly one
     active version per name. Both sqlite (>= 3.8) and PostgreSQL
     support ``WHERE`` predicates on partial indexes; the migration
     uses dialect-aware DDL so the same file works on both engines.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (CHAR(36)) and PostgreSQL
(native UUID) — same convention as the rest of the migrations in this
chain — and to express the partial index in dialect-specific DDL
because Alembic's ``op.create_index`` does not abstract ``WHERE``
predicates cross-dialect.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
# Branch off both currently-open heads (PR #89 cover_letter_style and
# PR #90 quick_filter) so this revision merges the chain back to a
# single linear head.
down_revision: str | Sequence[str] | None = ("7b1a4c5d8e2f", "f0e1a2b3c4d5")
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. Extend ``vacancy_matches`` with the LLM scoring fields.
    # ------------------------------------------------------------------
    with op.batch_alter_table("vacancy_matches") as batch:
        batch.add_column(sa.Column("explanation", sa.Text(), nullable=True))
        batch.add_column(sa.Column("prompt_version", sa.String(length=50), nullable=True))
        batch.add_column(sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True))

    # ------------------------------------------------------------------
    # 2. Create the ``prompt_versions`` table.
    # ------------------------------------------------------------------
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint(
            "name",
            "version",
            name=op.f("uq_prompt_versions_name_version"),
        ),
    )
    op.create_index(
        op.f("ix_prompt_versions_name"),
        "prompt_versions",
        ["name"],
        unique=False,
    )

    # ------------------------------------------------------------------
    # 3. Partial UNIQUE index — only one active version per name.
    # ------------------------------------------------------------------
    # Both sqlite (>= 3.8) and PostgreSQL accept a ``WHERE`` predicate
    # on ``CREATE UNIQUE INDEX``; the same DDL works on both engines,
    # so the migration uses ``op.execute`` to emit it verbatim.
    op.execute(
        sa.text(
            f"CREATE UNIQUE INDEX {op.f('ix_prompt_versions_one_active_per_name')} "
            "ON prompt_versions (name) WHERE is_active"
        )
    )


def downgrade() -> None:
    # Reverse the partial index first so the table can be dropped
    # without an ``IntegrityError`` (the partial index depends on the
    # table). Then drop the table, then revert the ``vacancy_matches``
    # extensions.
    op.drop_index(op.f("ix_prompt_versions_one_active_per_name"), table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_name"), table_name="prompt_versions")
    op.drop_table("prompt_versions")

    with op.batch_alter_table("vacancy_matches") as batch:
        batch.drop_column("scored_at")
        batch.drop_column("prompt_version")
        batch.drop_column("explanation")
