"""source_metrics: add source_metric_events table

Revision ID: a5b6c7d8e9f0
Revises: eb6c1c51520c
Create Date: 2026-06-17 11:00:00.000000

Adds the ``source_metric_events`` table that backs the
:class:`SourceMetricEventORM` model introduced in M7, issue #62.
Every public :class:`SourceService.ingest_*` call records four
rows (one per :class:`SourceMetricEventKind` — ``fetch``,
``normalize``, ``dedupe``, ``fail``) so the operator can see
per-source ingest behaviour over time.

Schema
------

* ``id``            — UUID primary key.
* ``source_name``   — stable source identifier (``"hh"``,
                      ``"habr"``, ``"telegram"``, ...).
* ``kind``          — one of the four :class:`SourceMetricEventKind`
                      values. Stored as ``VARCHAR(20)`` to leave
                      headroom for future kinds.
* ``count``         — number of items the event refers to.
                      ``0`` is a valid value.
* ``duration_ms``   — wall-clock duration of the ingest call in
                      milliseconds. The same value is shared by the
                      four events a single ingest call produces.
* ``timestamp``     — server-side ``CURRENT_TIMESTAMP`` at insert.
* ``metadata_json`` — JSON-encoded free-form context (the four
                      counts mirrored, plus any caller-supplied
                      keys). The slice uses JSON-encoded ``TEXT``
                      to keep the migration portable across sqlite
                      (``CHAR``) and PostgreSQL (``TEXT``/``JSONB``)
                      — same convention as
                      :class:`CoverLetterStyle` and
                      :class:`ApplyStatusHistory`.

Indexes
-------

* ``ix_source_metric_events_source_name_timestamp`` composite on
  ``(source_name, timestamp)`` backs
  :meth:`SqlSourceMetricRepository.query` and keeps the per-source
  timeline query cheap as the table grows.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and
PostgreSQL (native ``UUID``) — same convention as the rest of the
migrations in this chain. The branch points at both current heads
``eb6c1c51520c`` — search_profiles ``is_preferred``) so the chain
merges any subsequent branches into a single head.

.. note::
   M10 (issue #204) removed the HH OAuth / apply path, including the
   ``f1a2b3c4d5e6_hh_add_hh_resume_links_table`` migration. The
   ``down_revision`` above used to be the tuple
   ``("eb6c1c51520c", "f1a2b3c4d5e6")``; we now point only at
   ``eb6c1c51520c`` because the other branch is gone.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5b6c7d8e9f0"
down_revision: str | Sequence[str] | None = "eb6c1c51520c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "source_metric_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_name", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("duration_ms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("metadata_json", sa.Text(), nullable=False, server_default="{}"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_metric_events")),
    )
    op.create_index(
        "ix_source_metric_events_source_name_timestamp",
        "source_metric_events",
        ["source_name", "timestamp"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_source_metric_events_source_name_timestamp",
        table_name="source_metric_events",
    )
    op.drop_table("source_metric_events")
