"""cover_letter: add cover_letter_drafts table

Revision ID: a8c0f1d2e3b4
Revises: 9b1c2d3e4f56
Create Date: 2026-06-16 00:00:00.000000

Adds the ``cover_letter_drafts`` table that stores one row per cover
letter version, supporting the M3 "regenerate" workflow (issues #31 +
#32). The table is intentionally **not** unique on ``match_id``: each
regeneration creates a new row whose ``version`` is one above the
previous maximum, and the previous row's ``replaced_by_id`` is
back-linked to the new row.

* ``match_id``        — FK to ``vacancy_matches.id`` (owned by the
                        matches slice, issue #10). Cascades on
                        delete so a removed match leaves no orphans.
* ``user_id``         — FK to ``users.id`` (owned by the auth slice,
                        issue #11). Duplicated for cheap ownership
                        checks (the API never needs to join through
                        ``vacancy_matches`` to decide whether the
                        caller can see a draft).
* ``parent_draft_id`` / ``replaced_by_id`` — self-FKs that form a
                        doubly-linked list of the version history. The
                        columns are nullable: version 1 has no
                        parent; the latest version has no replacement.
                        ``ON DELETE SET NULL`` keeps the chain intact
                        if an intermediate version is ever removed.
* ``version``         — 1 for the first draft, increments by one with
                        every regeneration.
* ``text``            — the generated cover-letter body.
* ``style``           — the style key the generator was invoked with
                        (e.g. ``"friendly"``).
* ``user_comment``    — the human hint that triggered a regeneration
                        (e.g. ``"make it warmer"``).
* ``generation_prompt_hash`` — SHA-256 hex of the inputs that
                        produced ``text``. Audit only.

Indexes
-------

* ``ix_cover_letter_drafts_match_version`` (composite on
  ``match_id``, ``version``) — accelerates the
  "latest for this match" and "history for this match" queries that
  power the Telegram / web review surface.
* ``ix_cover_letter_drafts_user_id`` (single column) — used by the
  user-scoped listing that backs the daily digest (issue #35).

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8c0f1d2e3b4"
down_revision: str | Sequence[str] | None = "9b1c2d3e4f56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "cover_letter_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("style", sa.String(length=32), nullable=True),
        sa.Column("user_comment", sa.Text(), nullable=True),
        sa.Column("generation_prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("parent_draft_id", sa.String(length=36), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["vacancy_matches.id"],
            name=op.f("fk_cover_letter_drafts_match_id_vacancy_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cover_letter_drafts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_draft_id"],
            ["cover_letter_drafts.id"],
            name=op.f("fk_cover_letter_drafts_parent_draft_id_cover_letter_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["cover_letter_drafts.id"],
            name=op.f("fk_cover_letter_drafts_replaced_by_id_cover_letter_drafts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cover_letter_drafts")),
    )
    op.create_index(
        op.f("ix_cover_letter_drafts_match_version"),
        "cover_letter_drafts",
        ["match_id", "version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cover_letter_drafts_user_id"),
        "cover_letter_drafts",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_cover_letter_drafts_user_id"), table_name="cover_letter_drafts")
    op.drop_index(op.f("ix_cover_letter_drafts_match_version"), table_name="cover_letter_drafts")
    op.drop_table("cover_letter_drafts")
