"""cover_letter: add cover_letter_drafts table

Revision ID: b2c3d4e5f6a7
Revises: 9b1c2d3e4f56
Create Date: 2026-06-16 10:00:00.000000

Adds the ``cover_letter_drafts`` table that stores the **first** cover
letter generated for a :class:`VacancyMatch` (M3, issue #31).

Schema
------

* ``id``              — UUID primary key.
* ``match_id``        — FK to ``vacancy_matches.id`` (issue #10).
                        ``UNIQUE`` — the slice's contract is "one
                        draft per match"; a repeat call to
                        :meth:`CoverLetterService.generate_for_match`
                        mutates the existing row's content rather
                        than inserting a second one. Cascades on
                        delete so a removed match leaves no orphans.
* ``user_id``         — FK to ``users.id`` (issue #11). Duplicated
                        for cheap ownership checks; the slice never
                        has to join through ``vacancy_matches`` to
                        decide whether the caller can see a draft.
* ``content``         — the generated cover-letter body (markdown is
                        allowed; the renderer lives downstream).
* ``prompt_version``  — ``<name>@<semver>`` stamp. Format mirrors the
                        :class:`PromptVersion` value object.
* ``model_used``      — the LLM model name that produced ``content``.
                        ``NULL`` when the client does not expose a
                        model attribute.
* ``status``          — one of ``draft`` / ``regenerating`` /
                        ``final`` / ``sent`` / ``archived``. The
                        slice always creates rows in ``draft``;
                        downstream slices move them through the
                        lifecycle.
* ``created_at`` / ``updated_at`` — server-side timestamps.

Indexes
-------

* ``ix_cover_letter_drafts_user_id`` (single column on ``user_id``)
  backs the user-scoped listing that powers the daily digest and the
  review surface.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain. The branch is the single head at the time of writing
(``9b1c2d3e4f56`` — scoring's ``confidence`` column), so the chain
stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a7"
down_revision: str | Sequence[str] | None = "9b1c2d3e4f56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "cover_letter_drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="draft",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_cover_letter_drafts"),
        sa.UniqueConstraint("match_id", name="uq_cover_letter_drafts_match_id"),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["vacancy_matches.id"],
            name="fk_cover_letter_drafts_match_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_cover_letter_drafts_user_id",
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        "ix_cover_letter_drafts_user_id",
        "cover_letter_drafts",
        ["user_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_cover_letter_drafts_user_id", table_name="cover_letter_drafts")
    op.drop_table("cover_letter_drafts")
