"""cover_letter: add version column to cover_letter_drafts table

Revision ID: c4d5e6f7a8b9
Revises: 8f1c2d3e4f56
Create Date: 2026-06-16 13:00:00.000000

Adds the ``version`` column to the ``cover_letter_drafts`` table that
tracks the regeneration count for a draft. The M4 issue #40
``/regenerate <match_id>`` Telegram action uses the column to:

* stamp the new iteration on the ``COVER_LETTER_REGENERATED`` audit
  event (so the audit log is self-explanatory without a cross-table
  join);
* render the new version in the chat reply ("v2", "v3", ...).

Schema
------

* ``version`` — ``Integer``, ``NOT NULL``, default ``1``. The column
  mirrors the slice's contract: ``1`` on the initial generation,
  bumped on every call to
  :meth:`CoverLetterService.regenerate_for_match`. The migration uses
  ``server_default="1"`` so existing rows (from before M4 #40) read
  back as version ``1`` without an explicit data backfill; the
  ``default=1`` mirror on the model keeps in-memory fakes in sync.

The migration is hand-written (not autogenerated) to keep the
``Integer`` column portable across sqlite and PostgreSQL — same
convention as the rest of the migrations in this chain. The branch
is the single head at the time of writing (``8f1c2d3e4f56`` —
screening), so the chain stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4d5e6f7a8b9"
down_revision: str | Sequence[str] | None = "8f1c2d3e4f56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "cover_letter_drafts",
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )


def downgrade() -> None:
    op.drop_column("cover_letter_drafts", "version")
