"""learning: add learning_signals table for the M8 feedback store

Revision ID: c63d4a1b2e3f
Revises: eb6c1c51520c
Create Date: 2026-06-17 12:00:00.000000

Issue #63 (M8: Add learning signals from user rejections). This
revision introduces the ``learning_signals`` table that backs the
:class:`LearningSignalRepository` slice. The current producer is the
``/reject`` Telegram action (M4, issue #38); future producers will
include dismissals and "low-score" hits from the review queue.

Schema
------

The table has:

* ``id`` — server-generated UUID PK.
* ``user_id`` — UUID, non-null, indexed (per-user read path).
* ``match_id``, ``vacancy_id``, ``search_profile_id`` — UUIDs that
  carry the join keys to the ``vacancy_matches`` and downstream
  tables. The slice does not enforce ``ForeignKey`` constraints
  because it needs to outlive row deletion (a rejected match may be
  purged before the prompt-tuning pipeline reads the signal).
* ``rejection_reason`` — nullable ``Text``; the free-form text the
  user supplied with the ``/reject`` command.
* ``prompt_version`` — nullable ``String(50)``; the active prompt
  version the match was scored with (NULL when the match had never
  been through the LLM pipeline).
* ``score`` — nullable ``Float``; the score the match carried at
  reject time, in ``[0.0, 100.0]``. ``Float`` (not ``Integer``) so
  future LLM scoring passes can use a finer-grained value without
  another migration.
* ``signal_type`` — non-null ``String(32)``; the narrow
  discriminator (``rejection`` / ``dismissal`` / ``low_score``).
* ``created_at`` — server-side timestamp with timezone.

Two composite indexes back the two read paths:

* ``(user_id, created_at)`` — the per-user read path used by
  ``GET /learning/signals``.
* ``(prompt_version, created_at)`` — the per-prompt read path the
  future prompt-tuning pipeline will hit.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and
PostgreSQL (``UUID``) — same convention as the rest of the chain —
and to keep the table definition next to its documentation. It
branches off both currently-open heads
(``eb6c1c51520c`` — search_profiles is_preferred, and
``f1a2b3c4d5e6`` — hh resume links) so the chain stays linear.

.. note::
   M10 (issue #204) removed the HH OAuth / apply path, including the
   ``f1a2b3c4d5e6_hh_add_hh_resume_links_table`` migration. The
   ``down_revision`` above used to be the tuple
   ``("eb6c1c51520c", "f1a2b3c4d5e6")``; we now point only at
   ``eb6c1c51520c`` because the other branch is gone.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c63d4a1b2e3f"
# Originally branched off both currently-open heads to merge the chain.
# M10 dropped the ``f1a2b3c4d5e6`` migration, so the parent is now
# only ``eb6c1c51520c``.
down_revision: str | Sequence[str] | None = "eb6c1c51520c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "learning_signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("match_id", sa.String(length=36), nullable=False),
        sa.Column("vacancy_id", sa.String(length=36), nullable=False),
        sa.Column("search_profile_id", sa.String(length=36), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("signal_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_signals")),
    )
    # The two read paths the slice depends on. The single-column
    # index on ``user_id`` is implicit in the composite index on
    # (user_id, created_at), but PostgreSQL needs the column listed
    # explicitly for the planner to use the composite index for
    # user-only filters; sqlite handles either form. The two
    # composite indexes carry their own column implicitly.
    op.create_index(
        op.f("ix_learning_signals_user_id"),
        "learning_signals",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_signals_user_created"),
        "learning_signals",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_signals_prompt_created"),
        "learning_signals",
        ["prompt_version", "created_at"],
        unique=False,
    )


def downgrade() -> None:
    # Drop indexes first, then the table, so the downgrade is
    # symmetric to ``upgrade`` and a future re-upgrade works
    # cleanly.
    op.drop_index(op.f("ix_learning_signals_prompt_created"), table_name="learning_signals")
    op.drop_index(op.f("ix_learning_signals_user_created"), table_name="learning_signals")
    op.drop_index(op.f("ix_learning_signals_user_id"), table_name="learning_signals")
    op.drop_table("learning_signals")
