"""matches: add vacancy_matches table

Revision ID: d5f8a9b0c123
Revises: c23d4a1b2e3f
Create Date: 2026-06-15 03:00:00.000000

Adds the ``vacancy_matches`` table that joins canonical
:class:`Vacancy` rows to user-owned :class:`SearchProfile` rows. The
``(search_profile_id, vacancy_id)`` pair is unique so a re-ingest of
the same vacancy for a given profile is a no-op rather than a
duplicate; the ``(search_profile_id, status)`` composite index
accelerates the "show me all *new* matches for this profile" query
that powers the review queue.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (CHAR(36)) and PostgreSQL
(native UUID) — same convention as the rest of the migrations in
this chain.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5f8a9b0c123"
down_revision: str | Sequence[str] | None = "c23d4a1b2e3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "vacancy_matches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("search_profile_id", sa.String(length=36), nullable=False),
        sa.Column("vacancy_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            server_default="new",
        ),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("match_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_profile_id"],
            ["search_profiles.id"],
            name=op.f("fk_vacancy_matches_search_profile_id_search_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vacancy_id"],
            ["vacancies.id"],
            name=op.f("fk_vacancy_matches_vacancy_id_vacancies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vacancy_matches")),
        sa.UniqueConstraint(
            "search_profile_id",
            "vacancy_id",
            name=op.f("uq_vacancy_matches_profile_vacancy"),
        ),
    )
    op.create_index(
        op.f("ix_vacancy_matches_profile_status"),
        "vacancy_matches",
        ["search_profile_id", "status"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_vacancy_matches_profile_status"), table_name="vacancy_matches")
    op.drop_table("vacancy_matches")
