"""sources: add created_at indexes to vacancies

Revision ID: e2a3b4c5d6f7
Revises: 5b7c8d9e0f1a
Create Date: 2026-06-27 00:00:00.000000

Closes #259.

Every listing path on the ``vacancies`` table ends in
``ORDER BY created_at DESC``:

* :meth:`VacancyRepository.list_recent`           — ``ORDER BY created_at DESC LIMIT n``
* :meth:`VacancyRepository.list_with_filters`    — ``ORDER BY created_at DESC LIMIT/OFFSET``
* :meth:`VacancyRepository.list_by_source`       — ``WHERE source = :s ORDER BY created_at DESC``

Without indexes the planner falls back to a sequential scan plus an
in-DB sort, which scales linearly with row count. This revision adds
two indexes that let the planner satisfy those reads with an index
range scan and skip the sort step:

* ``ix_vacancies_created_at``                — single-column on
  ``created_at``; backs ``list_recent`` and ``list_with_filters``.
* ``ix_vacancies_source_created_at``         — composite ``(source,
  created_at)`` with ``source`` as the leading column; backs
  ``list_by_source`` so the equality predicate and the trailing
  ``created_at`` sort are both served by the same index.

The migration is hand-written (not autogenerated) to keep the chain
portable across sqlite (the dev/test default) and PostgreSQL (the
production target) — same convention as the rest of
``alembic/versions/*.py``. ``op.create_index`` is dialect-agnostic for
plain B-tree indexes, so no ``sa.String(36)`` shimming is needed here;
``created_at`` is ``DateTime(timezone=True)`` and ``source`` is
``String(50)`` in both dialects.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2a3b4c5d6f7"
down_revision: str | Sequence[str] | None = "5b7c8d9e0f1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_index(
        "ix_vacancies_created_at",
        "vacancies",
        ["created_at"],
    )
    op.create_index(
        "ix_vacancies_source_created_at",
        "vacancies",
        ["source", "created_at"],
    )


def downgrade() -> None:
    op.drop_index("ix_vacancies_source_created_at", table_name="vacancies")
    op.drop_index("ix_vacancies_created_at", table_name="vacancies")
