"""cover_letter_style: add cover_letter_styles table

Revision ID: f0e1a2b3c4d5
Revises: d5f8a9b0c123
Create Date: 2026-06-15 16:00:00.000000

Adds the ``cover_letter_styles`` table that stores per-user style
preferences for the M3 cover-letter generation slices (#31, #32). The
``user_id`` column is a foreign key to ``users.id`` (owned by the auth
slice, issue #11) and is unique: each user has at most one style row.

The ``focus_areas`` and ``avoid_phrases`` columns are stored as
JSON-encoded ``TEXT`` to keep the migration portable across sqlite
(``CHAR(36)`` for the user id) and PostgreSQL (``UUID``) without an
``ARRAY`` type. The repository layer owns the JSON encoding.

The migration is hand-written (not autogenerated) to keep the ``UUID``
columns portable across sqlite and PostgreSQL — same convention as the
rest of the migrations in this chain.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0e1a2b3c4d5"
down_revision: str | Sequence[str] | None = "d5f8a9b0c123"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "cover_letter_styles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "tone",
            sa.String(length=32),
            nullable=False,
            server_default="professional",
        ),
        sa.Column(
            "length",
            sa.String(length=16),
            nullable=False,
            server_default="medium",
        ),
        sa.Column(
            "focus_areas",
            sa.Text(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column(
            "avoid_phrases",
            sa.Text(),
            nullable=False,
            server_default="[]",
        ),
        sa.Column("extra_instructions", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cover_letter_styles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cover_letter_styles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_cover_letter_styles_user_id")),
    )
    op.create_index(
        op.f("ix_cover_letter_styles_user_id"),
        "cover_letter_styles",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_cover_letter_styles_user_id"), table_name="cover_letter_styles")
    op.drop_table("cover_letter_styles")
