"""hh: add hh_resume_links table

Revision ID: f1a2b3c4d5e6
Revises: 9f1a2b3c4d5e
Create Date: 2026-06-16 20:00:00.000000

Adds the ``hh_resume_links`` table that backs the
:class:`~job_apply.features.hh.resumes.HhResumeLink` model introduced in
M2, issue #21. The table stores the link between a local user and an
hh.ru resume, ready for the next slice to fetch full-text content and
populate ``local_resume_id``.

Schema
------

* ``id``              — UUID primary key.
* ``user_id``         — FK to ``users.id`` (``ondelete=CASCADE`` so a
                        hard-deleted user takes their hh resume links
                        with it).
* ``local_resume_id`` — FK to ``resumes.id``
                        (``ondelete=SET NULL`` so a hard-deleted local
                        resume does *not* take its hh link with it —
                        the link still tracks the external id).
* ``hh_resume_id``    — hh.ru's external resume id, ``VARCHAR(50)``.
* ``title``           — hh.ru's human-readable title, ``VARCHAR(255)``.
* ``updated_at_hh``   — hh.ru's last-modified timestamp (no value when
                        hh.ru omits it from the response).
* ``last_synced_at``  — when the local sync last fetched this row.

Indexes
-------

* ``uq_hh_resume_links_user_hh_resume`` on ``(user_id, hh_resume_id)`` —
  the unique key the sync service matches on. Keeping it as a unique
  constraint (not just an index) means the database enforces "one
  link per hh resume per user" regardless of how many concurrent
  syncs run.
* ``ix_hh_resume_links_user_id`` on ``(user_id)`` — backs the
  ``GET /hh/resumes`` listing endpoint.

The migration is hand-written (not autogenerated) to keep the
``UUID`` columns portable across sqlite (``CHAR(36)``) and PostgreSQL
(native ``UUID``) — same convention as the rest of the migrations in
this chain. The branch follows on from ``9f1a2b3c4d5e``
(``apply_rate_limit_events``) so the chain stays linear.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1a2b3c4d5e6"
down_revision: str | Sequence[str] | None = "9f1a2b3c4d5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "hh_resume_links",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("local_resume_id", sa.String(length=36), nullable=True),
        sa.Column("hh_resume_id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("updated_at_hh", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_hh_resume_links"),
        sa.UniqueConstraint(
            "user_id",
            "hh_resume_id",
            name="uq_hh_resume_links_user_hh_resume",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_hh_resume_links_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["local_resume_id"],
            ["resumes.id"],
            name="fk_hh_resume_links_local_resume_id",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        op.f("ix_hh_resume_links_user_id"),
        "hh_resume_links",
        ["user_id"],
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_hh_resume_links_user_id"), table_name="hh_resume_links")
    op.drop_table("hh_resume_links")
