"""Scoring review vertical slice (M8, issue #68).

The slice exposes a manual review queue for low-confidence matches
generated by the LLM scoring pipeline. It is read-mostly: one read
endpoint surfaces the matches an operator should look at, and one
write endpoint lets the operator attach a free-form note to a match
without changing the match's status.

Public surface
--------------

* :class:`LowConfidenceMatch` — frozen dataclass the queue returns.
* :class:`ScoringReviewQueue` — Protocol the service depends on.
* :class:`InMemoryScoringReviewQueue` — list-backed fake for tests.
* :class:`SqlScoringReviewQueue` — production implementation backed
  by a SQLAlchemy ``Session``.
* :class:`ScoringReviewService` — facade the API layer uses.
* :class:`LowConfidenceMatchRead` / :class:`ScoringReviewNoteCreate` /
  :class:`ScoringReviewNoteResponse` — wire-format Pydantic models.
* :func:`low_confidence_match_to_read` /
  :func:`scoring_review_note_response` — bridge functions.
* :data:`router` — FastAPI router (mounted at ``/admin/scoring-review``).

The slice deliberately re-uses the existing ``vacancy_matches`` table
and the existing ``audit_logs`` table: the reviewer note is stored as
an :attr:`AuditEventType.MATCH_REVIEWED` row whose ``details`` JSON
carries both the ``match_id`` and the ``note`` text. No new columns,
no new migrations.
"""

from __future__ import annotations

from job_apply.features.scoring_review.models import LowConfidenceMatch
from job_apply.features.scoring_review.repository import (
    InMemoryScoringReviewQueue,
    ScoringReviewQueue,
    SqlScoringReviewQueue,
)
from job_apply.features.scoring_review.schemas import (
    LowConfidenceMatchRead,
    ScoringReviewNoteCreate,
    ScoringReviewNoteResponse,
    low_confidence_match_to_read,
    scoring_review_note_response,
)
from job_apply.features.scoring_review.service import ScoringReviewService

__all__ = [
    "InMemoryScoringReviewQueue",
    "LowConfidenceMatch",
    "LowConfidenceMatchRead",
    "ScoringReviewNoteCreate",
    "ScoringReviewNoteResponse",
    "ScoringReviewQueue",
    "ScoringReviewService",
    "SqlScoringReviewQueue",
    "low_confidence_match_to_read",
    "scoring_review_note_response",
]
